version: '3'
services:
  selenium:
    build:
      context: .
      shm_size: '2gb'
    restart: 'no'
    volumes:
      - .:/usr/src/app
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2gb'
    command: tail -F anything
  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444